# Generated by Django 3.2.5 on 2024-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_auto_20241207_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='additional_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
